# Generated by Django 5.2.4 on 2025-08-19 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_localizacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motoboy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=False)),
            ],
        ),
    ]
